input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => [
      "security-auth-log",
      "nginx-access-log",
      "docker-container-log"
    ]
    group_id => "logstash-etl-consumer"
    codec => plain
  }
}

filter {
  mutate {
    add_field => {
      "raw_message" => "%{message}"
      "pipeline_stage" => "raw_ingest"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "etl-raw-log-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
